In [58]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from textblob import TextBlob
from numpy import dot 
from numpy.linalg import norm
from itertools import combinations
from sklearn.metrics.pairwise import cosine_similarity
my_text = TextBlob("i live there since last day ")
#my_text.words
blob = TextBlob("i am graat at spelling")
#print(blob.correct())
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
cv = CountVectorizer()
x = cv.fit_transform(corpus)          
#print(x.toarray())           
data = pd.DataFrame(x.toarray(), columns = cv.get_feature_names())  
#print(data)
cosine = lambda v1, v2 : dot(v1,v2) / (norm(v1) * norm(v2))
cosine([1,1,1,0],[1,1,0,1])
tfidf = TfidfVectorizer()
x = tfidf.fit_transform(corpus)
dt = pd.DataFrame(x.toarray(), columns = tfidf.get_feature_names())
#print(dt)
corp = ['The weather is hot under the sun',
'I make my hot chocolate with milk',
'One hot encoding',
'I will have a chai latte with milk',
'There is a hot sale today']
cv = CountVectorizer()
x = cv.fit_transform(corp).toarray()                    
data = pd.DataFrame(x, columns = cv.get_feature_names()) 
pairs = list(combinations(range(len(corp)),2))
combos = [(corp[a_index],corp[b_index]) for (a_index, b_index) in pairs]
results = [cosine_similarity([x[a_index]],[x[b_index]]) for (a_index, b_index) in pairs]

sorted(zip(results,combos),reverse = True) 

[(array([[0.33333333]]),
  ('I make my hot chocolate with milk', 'I will have a chai latte with milk')),
 (array([[0.2981424]]),
  ('The weather is hot under the sun', 'There is a hot sale today')),
 (array([[0.25819889]]), ('One hot encoding', 'There is a hot sale today')),
 (array([[0.23570226]]),
  ('I make my hot chocolate with milk', 'One hot encoding')),
 (array([[0.19245009]]),
  ('The weather is hot under the sun', 'One hot encoding')),
 (array([[0.18257419]]),
  ('I make my hot chocolate with milk', 'There is a hot sale today')),
 (array([[0.13608276]]),
  ('The weather is hot under the sun', 'I make my hot chocolate with milk')),
 (array([[0.]]),
  ('The weather is hot under the sun', 'I will have a chai latte with milk')),
 (array([[0.]]), ('One hot encoding', 'I will have a chai latte with milk')),
 (array([[0.]]),
  ('I will have a chai latte with milk', 'There is a hot sale today'))]